### ISSUE TITLE
Attribute "Unit" missing for thickness parameter in many estes_ps2 nose cones

### ISSUE THREAD

**Issue by davesrocketshop** [dbcook/openrocket-database#10]
Example:

      <NoseCone>
        <Manufacturer>Estes</Manufacturer>
        <PartNumber>72695</PartNumber>
        <Description>Nose cone, plastic, 3.0" series, 8.0" len, PN 72695</Description>
        <Material Type="BULK">Polystyrene, cast, bulk</Material>
        <Filled>false</Filled>
        <Shape>OGIVE</Shape>
        <OutsideDiameter Unit="in">3.000</OutsideDiameter>
        <ShoulderDiameter Unit="in">2.920</ShoulderDiameter>
        <ShoulderLength Unit="in">3.0</ShoulderLength>
        <Length Unit="in">8.0</Length>
        <Thickness>0.125</Thickness>
      </NoseCone>

For most nose cones, this would have

     <Thickness  Unit="in">0.125</Thickness>

This occurs inconsistent;y in estes_ps2.orc

**Comment by davesrocketshop** [comment]
<TubeCoupler>
        <Manufacturer>Estes</Manufacturer>
        <PartNumber>30189</PartNumber>
        <Description>Tube coupler, 2.5" series, paper, kraft, PN 30189</Description>
        <Material Type="BULK">Fiber, bulk</Material>
        <InsideDiameter Unit="in">2,360</InsideDiameter>
        <OutsideDiameter Unit="in">2.420</OutsideDiameter>
        <Length Unit="in">4.0</Length>
      </TubeCoupler>

InsideDiameter uses comma for decimal

**Comment by davesrocketshop** [comment]
estes_ps2

      <TubeCoupler>
        <Manufacturer>Estes</Manufacturer>
        <PartNumber>31800</PartNumber>
        <Description>Tube coupler, 3.0" series, paper, PN 31800</Description>
        <Material Type="BULK">Fiber, bulk</Material>
        <InsideDiameter Unit="in">2,860</InsideDiameter> - comma for decimal
        <OutsideDiameter Unit="in">2.920</OutsideDiameter>
        <Length Unit="in">4.0</Length>
      </TubeCoupler>

generic_matrials      

        <Material UnitsOfMeasure="kg/m3">
            <Name>Water, bulk</Name>
            <Density>>1000.0</Density> extra '>'
            <Type>BULK</Type>
        </Material>

madcow

        <Transition>
            <Manufacturer>Madcow</Manufacturer>
            <PartNumber>BTC2629 [R]</PartNumber>
            <Description>Tail cone, balsa, 2.6in to 29mm, decreasing</Description>
            <Material Type="BULK">Balsa, bulk, 8 lb/ft3</Material>
            <Shape>CONICAL</Shape>
            <Filled>true</Filled>
            <Mass unit="oz">0.56</Mass>       - 'unit' instead of 'Unit', multiple places
            <ForeOutsideDiameter Unit="in">2.640</ForeOutsideDiameter>
            <ForeShoulderDiameter Unit="in">2.548</ForeShoulderDiameter>
            <ForeShoulderLength Unit="in">1.25</ForeShoulderLength>
            <AftOutsideDiameter Unit="in">2.0</AftOutsideDiameter>
            <AftShoulderDiameter Unit="in">1.218</AftShoulderDiameter>
            <AftShoulderLength Unit="in">0.0</AftShoulderLength>
            <Length Unit="in">2.5</Length>
        </Transition>
        <CenteringRing>
          <Manufacturer>Madcow</Manufacturer>
          <PartNumber>FCR2629A-GDL3</PartNumber>
          <Description>Centering ring, G10 FG, aft (no hole), 29mm FG MMT to 2.6in FG</Description>
          <Material Type="BULK">Fiberglass, G10, bulk</Material>
          <InsideDiameter Unit="in">.1.258</InsideDiameter> - extra '.' at the beginning, multiple occurences
          <OutsideDiameter Unit="in">2.557</OutsideDiameter>
          <Length Unit="in">0.092</Length>
        </CenteringRing>

semroc

    <NoseCone>
      <Manufacturer>SEMROC</Manufacturer>
      <PartNumber>BNC-30C</PartNumber>
      <Description>Nose cone, balsa, BNC-30C, 0.75", spherical</Description>
      <Material Type="BULK">Balsa, bulk, 7lb/ft3</Material>
      <Filled>true</Filled>
      <Shape>ELLIPSOID</Shape>
      <OutsideDiameter Unit="in">0.0.767</OutsideDiameter> - extra leading '0.', multiple occurences
      <ShoulderDiameter Unit="in">0.723</ShoulderDiameter>
      <ShoulderLength Unit="in">0.375</ShoulderLength>
      <Length Unit="in">0.75</Length>
    </NoseCone>

**Comment by dbcook** [comment]
Good catches!  Hopefully I can make some progress on those this weekend.

**Comment by dbcook** [comment]
Well that turned out to be really easy.  All fixed, release 0.9.3.3 pushed.
