### ISSUE TITLE
BMS discrepancies and missing data

### ISSUE THREAD

**Issue by ghost** [dbcook/openrocket-database#16]
There is a size mis-match in BMS BNC60MS Nosecone. the text says its 2.5" but the pdf drawing says its 4.5", I tend to believe that 4.5 is correct.

**Comment by ghost** [comment]
Same issue for BNC70AJ text is 4.4" drawing is 4.5
also BNC80BBH

**Comment by dbcook** [comment]
The 0.1 delta on the BNC70AJ is not a big error - but it should be mentioned in the comment for the item.  For reference the Estes BNC-70AJ was 4.25" long, so neither of the BMS numbers actually matches the original.  We need to put a note about that on the spreadsheet we're going to send Bill.

The 60MS is easily resolved:  it's for a Big Bertha; RocketReviews documents it as 2.5" long and the BMS drawing actually shows the shape which is about 2.5" long on the scale.  The error is only on the text in the BMS drawing, so I would use 2.5" and make a note in the comment for the item in the XML.

For the 80BBH, I don't see a problem.  The BMS website table and drawing both show the correct 4.0" length (the Estes PNC-80BB is 4.0" long).  The BMS cone has 2.640 diameter but that is to match their heavy wall tube which is thicker than the Estes standard BT-80.  BTW the PNC-80BB listed right above the BNC80BBH *is* the Estes PNC-80BB; BMS doesn't make their own plastic parts.

**Comment by ghost** [comment]
I changed the 60MS to the 2.5". You are correct I don't know what the the problem was ion the 80BBH. I want leave this issue open until we get all the data from Bill

**Comment by dbcook** [comment]
I've reviewed the BMS spreadsheet and shared it with Bill Saindon.  I took out the PNC80BB because that's actually the Estes part, and added a question about the source of the other 3.0" plastic nose cone since I don't think Bill actually makes plastic parts.

**Comment by ghost** [comment]
BMS.ORC updated with Bill Saindon supplied data. This should close out this issue.

**Comment by ghost** [comment]
All data updated

**Comment by dbcook** [comment]
bms.orc has not made it into my master branch.  Stephen can you generate a pull request please?

**Comment by ghost** [comment]
I have no idea how to do that.

**Comment by dbcook** [comment]
Just send me a link to your file in your repo then (make sure it's the
correct branch if you have branches)...I'll grab it and insert into master.

-Dave

**Comment by ghost** [comment]
I can do that but I really would like to know the correct way to do it


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by dbcook** [comment]
Hi Stephen,

Here are the official instructions.  This should apply directly to you
creating a PR from your fork.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

-Dave

**Comment by ghost** [comment]
OK, I did the draft pull request


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by dbcook** [comment]
Catching up on this...I finished checking the new BMS file and merged it to master as v1.0.0.1 back in December.  We are now on 1.0.0.2 with corrections to remove duplicate listings for OEM reseller parts.
