### ISSUE TITLE
ASP parts

### ISSUE THREAD

**Issue by ghost** [dbcook/openrocket-database#19]
Include ASP parts in database from https://www.asp-rocketry.com/

**Comment by dbcook** [comment]
Looks like we could list tubes (they give a good chart, hooray), couplers,
plywood bulkheads, and the Micromax plastic nose cones.  However there are
missing-data problems with all the balsa parts (no shoulder lengths given
for any of them), and the larger non-Estes plastic nose cones (no shoulder
length or mass).  For the plywood CRs, exact diameters are not specified so
they would have to be referenced to the tubes.  Lengths are missing for the
fiber CRs.  OD not given for launch lugs.  We can get roughly half of their
parts covered without additional information.

**Comment by ghost** [comment]
Sent email to ASP about missing data and got a response that they are out of the office until 9/30

**Comment by dbcook** [comment]
I think you said in an email that Andy was not planning to assist.  If that's the case we should close this as not planned.

**Comment by ghost** [comment]
You are correct, so this needs to be closed

**Comment by ghost** [comment]
No Help from ASP

**Comment by dbcook** [comment]
Closing due to missing data and vendor support not forthcoming
