### ISSUE TITLE
Parsing error

### ISSUE THREAD

**Issue by mrnic3** [dbcook/openrocket-database#3]
Hi,

when I follow the manual I get a parsing error of the orc files.
Tested it on windows and linux.

Any hint what I am doing wrong?

It does no have any effect wether I clean the jar upfront or not.

BR,
nice

**Comment by mrnic3** [comment]
---------- Bug report ----------

Please include a description about what actions you were performing when the exception occurred:




Include your email address (optional; it helps if we can contact you in case we need additional information):




(Do not modify anything below this line.)
---------- Exception stack trace ----------
net.sf.openrocket.util.BugException: BUG: Unable to parse file: bluetube.orc
	at net.sf.openrocket.preset.xml.OpenRocketComponentLoader.load(OpenRocketComponentLoader.java:38)
	at net.sf.openrocket.database.ComponentPresetDatabaseLoader.loadFile(ComponentPresetDatabaseLoader.java:98)
	at net.sf.openrocket.database.ComponentPresetDatabaseLoader.loadDatabase(ComponentPresetDatabaseLoader.java:83)
	at net.sf.openrocket.database.AsynchronousDatabaseLoader.doLoad(AsynchronousDatabaseLoader.java:103)
	at net.sf.openrocket.database.AsynchronousDatabaseLoader.access$100(AsynchronousDatabaseLoader.java:8)
	at net.sf.openrocket.database.AsynchronousDatabaseLoader$LoadingThread.run(AsynchronousDatabaseLoader.java:126)
Caused by: javax.xml.bind.UnmarshalException
 - with linked exception:
[org.xml.sax.SAXParseException; lineNumber: 634; columnNumber: 11; The element type "Components" must be terminated by the matching end-tag "</Components>".]
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:563)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:249)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:214)
	at net.sf.openrocket.preset.xml.OpenRocketComponentSaver.fromOpenRocketComponent(OpenRocketComponentSaver.java:150)
	at net.sf.openrocket.preset.xml.OpenRocketComponentSaver.unmarshalFromOpenRocketComponent(OpenRocketComponentSaver.java:117)
	at net.sf.openrocket.preset.xml.OpenRocketComponentLoader.load(OpenRocketComponentLoader.java:34)
	... 5 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 634; columnNumber: 11; The element type "Components" must be terminated by the matching end-tag "</Components>".
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1473)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1749)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	... 11 more

---------- Thread information ----------
Thread[DatabaseLoadingThread,1,main]

---------- System information ----------
OpenRocket version: 15.03
OpenRocket source: default
OpenRocket location: /home/mrnic3/OpenRocket-15.03-nopresets.jar
JOGL version: 2.1.5
Current default locale: en_US
System properties:
  awt.toolkit=sun.awt.X11.XToolkit
  file.encoding=UTF-8
  file.encoding.pkg=sun.io
  file.separator=/
  java.awt.graphicsenv=sun.awt.X11GraphicsEnvironment
  java.awt.printerjob=sun.print.PSPrinterJob
  java.class.path=OpenRocket-15.03-nopresets.jar
  java.class.version=52.0
  java.endorsed.dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/endorsed
  java.ext.dirs=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/ext:/usr/java/packages/lib/ext
  java.home=/usr/lib/jvm/java-8-openjdk-amd64/jre
  java.io.tmpdir=/tmp
  java.library.path=/home/mrnic3/catkin_ws/devel/lib:/opt/ros/kinetic/lib:/opt/ros/kinetic/lib/x86_64-linux-gnu:/usr/java/packages/lib/amd64:/usr/lib/x86_64-linux-gnu/jni:/lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu:/usr/lib/jni:/lib:/usr/lib
  java.runtime.name=OpenJDK Runtime Environment
  java.runtime.version=1.8.0_275-8u275-b01-0ubuntu1~16.04-b01
  java.specification.name=Java Platform API Specification
  java.specification.vendor=Oracle Corporation
  java.specification.version=1.8
  java.vendor=Private Build
  java.vendor.url=http://java.oracle.com/
  java.vendor.url.bug=http://bugreport.sun.com/bugreport/
  java.version=1.8.0_275
  java.vm.info=mixed mode
  java.vm.name=OpenJDK 64-Bit Server VM
  java.vm.specification.name=Java Virtual Machine Specification
  java.vm.specification.vendor=Oracle Corporation
  java.vm.specification.version=1.8
  java.vm.vendor=Private Build
  java.vm.version=25.275-b01
  jnlp.jogamp.tmp.cache.root=jln2146112948569171614
  line.separator=\u000a
  os.arch=amd64
  os.name=Linux
  os.version=4.15.0-128-generic
  path.separator=:
  sun.arch.data.model=64
  sun.awt.enableExtraMouseButtons=true
  sun.awt.exception.handler=net.sf.openrocket.gui.main.SwingExceptionHandler$AwtHandler
  sun.boot.class.path=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/resources.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/rt.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/sunrsasign.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jsse.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jce.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/charsets.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/jfr.jar:/usr/lib/jvm/java-8-openjdk-amd64/jre/classes
  sun.boot.library.path=/usr/lib/jvm/java-8-openjdk-amd64/jre/lib/amd64
  sun.cpu.endian=little
  sun.cpu.isalist=
  sun.desktop=gnome
  sun.font.fontmanager=sun.awt.X11FontManager
  sun.io.unicode.encoding=UnicodeLittle
  sun.java.command=OpenRocket-15.03-nopresets.jar
  sun.java.launcher=SUN_STANDARD
  sun.jnu.encoding=UTF-8
  sun.management.compiler=HotSpot 64-Bit Tiered Compilers
  sun.os.patch.level=unknown
  user.country=US
  user.dir=/home/mrnic3
  user.home=/home/mrnic3
  user.language=en
  user.name=mrnic3
  user.timezone=Europe/Berlin
---------- Error log ----------
   1      0.000 INFO   (SwingStartup.java:61) Starting up OpenRocket version 15.03
   2      0.000 INFO   (SwingStartup.java:64) Checking for graphics head
   3      0.037 INFO   (SwingStartup.java:75) Moving startup to EDT
   4      0.077 INFO   (SwingStartup.java:129) Initializing the splash screen
   5      0.134 INFO   (SwingStartup.java:133) Registering exception handler
   6      0.138 INFO   (SwingStartup.java:139) Loading databases
   7      0.550 INFO   (TranslatorProvider.java:49) Using default locale en_US
   8      0.556 INFO   (TranslatorProvider.java:61) Set up translation for locale en_US, debug.currentFile=messages.properties
   9      0.557 INFO   (ComponentPresetDatabaseLoader.java:51) Loading component presets from datafiles/presets
  10      0.558 DEBUG  (JarUtil.java:40) Found jar file using codeSource
  11      0.559 INFO   (SwingStartup.java:151) Starting update check
  12      0.560 INFO   (MotorDatabaseLoader.java:55) Starting reading serialized motor database
  13      0.560 DEBUG  (JarUtil.java:40) Found jar file using codeSource
  14      0.560 INFO   (SwingStartup.java:160) Setting best LAF
  15      0.565 DEBUG  (MotorDatabaseLoader.java:83) Reading motors from file datafiles/thrustcurves/thrustcurves.ser
  16      0.569 ERROR  (DirectoryIterator.java:139) Error opening directory from URL jar:file:/home/mrnic3/OpenRocket-15.03-nopresets.jar!/datafiles/presets
  17      0.569 ERROR  (DirectoryIterator.java:152) Error opening directory datafiles/presets
  18      0.569 DEBUG  (ComponentPresetDatabaseLoader.java:96) loading from file: generic_materials.orc
  19      0.570 DEBUG  (OpenRocketComponentLoader.java:26) Loading presets from file generic_materials.orc
  20      0.716 DEBUG  (OpenRocketComponentLoader.java:35) ComponentPreset file generic_materials.orc contained 0 presets
  21      0.716 DEBUG  (ComponentPresetDatabaseLoader.java:96) loading from file: bluetube.orc
  22      0.716 DEBUG  (OpenRocketComponentLoader.java:26) Loading presets from file bluetube.orc
  23      0.734 ERROR  (SwingExceptionHandler.java:48) Handling uncaught exception on thread=Thread[DatabaseLoadingThread,1,main]
   > net.sf.openrocket.util.BugException: BUG: Unable to parse file: bluetube.orc
   > 	at net.sf.openrocket.preset.xml.OpenRocketComponentLoader.load(OpenRocketComponentLoader.java:38)
   > 	at net.sf.openrocket.database.ComponentPresetDatabaseLoader.loadFile(ComponentPresetDatabaseLoader.java:98)
   > 	at net.sf.openrocket.database.ComponentPresetDatabaseLoader.loadDatabase(ComponentPresetDatabaseLoader.java:83)
   > 	at net.sf.openrocket.database.AsynchronousDatabaseLoader.doLoad(AsynchronousDatabaseLoader.java:103)
   > 	at net.sf.openrocket.database.AsynchronousDatabaseLoader.access$100(AsynchronousDatabaseLoader.java:8)
   > 	at net.sf.openrocket.database.AsynchronousDatabaseLoader$LoadingThread.run(AsynchronousDatabaseLoader.java:126)
   > Caused by: javax.xml.bind.UnmarshalException
   >  - with linked exception:
   > [org.xml.sax.SAXParseException; lineNumber: 634; columnNumber: 11; The element type "Components" must be terminated by the matching end-tag "</Components>".]
   > 	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
   > 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:563)
   > 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:249)
   > 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
   > 	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
   > 	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:214)
   > 	at net.sf.openrocket.preset.xml.OpenRocketComponentSaver.fromOpenRocketComponent(OpenRocketComponentSaver.java:150)
   > 	at net.sf.openrocket.preset.xml.OpenRocketComponentSaver.unmarshalFromOpenRocketComponent(OpenRocketComponentSaver.java:117)
   > 	at net.sf.openrocket.preset.xml.OpenRocketComponentLoader.load(OpenRocketComponentLoader.java:34)
   > 	... 5 more
   > Caused by: org.xml.sax.SAXParseException; lineNumber: 634; columnNumber: 11; The element type "Components" must be terminated by the matching end-tag "</Components>".
   > 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
   > 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
   > 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
   > 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
   > 	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1473)
   > 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1749)
   > 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
   > 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
   > 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
   > 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
   > 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
   > 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
   > 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
   > 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
   > 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
   > 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
   > 	... 11 more
  24      0.734 STDERR (SwingExceptionHandler.java:49) net.sf.openrocket.util.BugException: BUG: Unable to parse file: bluetube.orc
  25      0.734 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.preset.xml.OpenRocketComponentLoader.load(OpenRocketComponentLoader.java:38)
  26      0.734 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.database.ComponentPresetDatabaseLoader.loadFile(ComponentPresetDatabaseLoader.java:98)
  27      0.734 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.database.ComponentPresetDatabaseLoader.loadDatabase(ComponentPresetDatabaseLoader.java:83)
  28      0.734 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.database.AsynchronousDatabaseLoader.doLoad(AsynchronousDatabaseLoader.java:103)
  29      0.735 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.database.AsynchronousDatabaseLoader.access$100(AsynchronousDatabaseLoader.java:8)
  30      0.735 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.database.AsynchronousDatabaseLoader$LoadingThread.run(AsynchronousDatabaseLoader.java:126)
  31      0.735 STDERR (SwingExceptionHandler.java:49) Caused by: javax.xml.bind.UnmarshalException
  32      0.735 STDERR (SwingExceptionHandler.java:49)  - with linked exception:
  33      0.735 STDERR (SwingExceptionHandler.java:49) [org.xml.sax.SAXParseException; lineNumber: 634; columnNumber: 11; The element type "Components" must be terminated by the matching end-tag "</Components>".]
  34      0.735 STDERR (SwingExceptionHandler.java:49) 	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.createUnmarshalException(AbstractUnmarshallerImpl.java:335)
  35      0.735 STDERR (SwingExceptionHandler.java:49) 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.createUnmarshalException(UnmarshallerImpl.java:563)
  36      0.735 STDERR (SwingExceptionHandler.java:49) 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:249)
  37      0.735 STDERR (SwingExceptionHandler.java:49) 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
  38      0.735 STDERR (SwingExceptionHandler.java:49) 	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
  39      0.735 STDERR (SwingExceptionHandler.java:49) 	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:214)
  40      0.735 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.preset.xml.OpenRocketComponentSaver.fromOpenRocketComponent(OpenRocketComponentSaver.java:150)
  41      0.735 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.preset.xml.OpenRocketComponentSaver.unmarshalFromOpenRocketComponent(OpenRocketComponentSaver.java:117)
  42      0.735 STDERR (SwingExceptionHandler.java:49) 	at net.sf.openrocket.preset.xml.OpenRocketComponentLoader.load(OpenRocketComponentLoader.java:34)
  43      0.735 STDERR (SwingExceptionHandler.java:49) 	... 5 more
  44      0.735 STDERR (SwingExceptionHandler.java:49) Caused by: org.xml.sax.SAXParseException; lineNumber: 634; columnNumber: 11; The element type "Components" must be terminated by the matching end-tag "</Components>".
  45      0.735 STDERR (SwingExceptionHandler.java:49) 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
  46      0.736 STDERR (SwingExceptionHandler.java:49) 	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
  47      0.736 STDERR (SwingExceptionHandler.java:49) 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
  48      0.736 STDERR (SwingExceptionHandler.java:49) 	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
  49      0.736 STDERR (SwingExceptionHandler.java:49) 	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1473)
  50      0.736 STDERR (SwingExceptionHandler.java:49) 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanEndElement(XMLDocumentFragmentScannerImpl.java:1749)
  51      0.736 STDERR (SwingExceptionHandler.java:49) 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2967)
  52      0.736 STDERR (SwingExceptionHandler.java:49) 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
  53      0.736 STDERR (SwingExceptionHandler.java:49) 	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
  54      0.736 STDERR (SwingExceptionHandler.java:49) 	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
  55      0.736 STDERR (SwingExceptionHandler.java:49) 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:842)
  56      0.736 STDERR (SwingExceptionHandler.java:49) 	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:771)
  57      0.736 STDERR (SwingExceptionHandler.java:49) 	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
  58      0.736 STDERR (SwingExceptionHandler.java:49) 	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
  59      0.736 STDERR (SwingExceptionHandler.java:49) 	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
  60      0.736 STDERR (SwingExceptionHandler.java:49) 	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
  61      0.736 STDERR (SwingExceptionHandler.java:49) 	... 11 more
  62      0.736 INFO   (SwingExceptionHandler.java:64) Exception handler not on EDT, invoking dialog on EDT
  63      0.758 INFO   (MotorDatabaseLoader.java:61) Ending reading serialized motor database, motorCount=1721
  64      0.758 INFO   (MotorDatabaseLoader.java:64) Starting reading user-defined motors
  65      0.759 INFO   (MotorDatabaseLoader.java:74) Ending reading user-defined motors, motorCount=1721
  66      0.770 INFO   (SwingStartup.java:172) Opening main application window
  67      0.778 INFO   (BasicFrame.java:1518) New action initiated
  68      0.782 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.rocketcomponent.Configuration@656fff7a, current number of listeners is 1
  69      0.785 DEBUG  (Rocket.java:394) Firing rocket change event ComponentChangeEvent[tree]
  70      0.786 INFO   (OpenRocketDocument.java:414) Clearing undo history of net.sf.openrocket.document.OpenRocketDocument@136b7d40
  71      0.786 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.document.OpenRocketDocument@136b7d40, current number of listeners is 2
  72      0.796 DEBUG  (BasicFrame.java:170) Instantiating new BasicFrame
  73      0.902 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.gui.main.SimulationPanel$22@71d19508, current number of listeners is 3
  74      0.914 DEBUG  (Icons.java:24) Starting to load icons
  75      0.936 DEBUG  (Icons.java:94) Icons loaded
  76      0.937 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.gui.main.RocketActions$2@1971803c, current number of listeners is 4
  77      0.937 DEBUG  (BasicFrame.java:193) Constructing the BasicFrame UI
  78      0.954 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.gui.main.componenttree.ComponentTreeModel@24c9fbcd, current number of listeners is 5
  79      0.974 DEBUG  (UpdateInfoRetriever.java:173) Update response code: 404
  80      0.974 WARN   (UpdateInfoRetriever.java:184) Unknown server response code: 404
  81      1.056 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.MotorConfigurationPanel$6@62468648, current number of listeners is 6
  82      1.170 VBOSE  (AbstractChangeSource.java:25) Adding change listeners, listener count is now 1
  83      1.170 VBOSE  (DoubleModel.java:890) DoubleModel[MotorRowFilter:MinimumLength] adding listener (total 1): javax.swing.JSpinner$ModelListener@f5965ca
  84      1.174 VBOSE  (DoubleModel.java:890) DoubleModel[MotorRowFilter:MinimumLength] adding listener (total 2): net.sf.openrocket.gui.dialogs.motor.thrustcurve.MotorFilterPanel$11@45582ef7
  85      1.175 VBOSE  (AbstractChangeSource.java:25) Adding change listeners, listener count is now 2
  86      1.175 VBOSE  (DoubleModel.java:890) DoubleModel[MotorRowFilter:MaximumLength] adding listener (total 1): javax.swing.JSpinner$ModelListener@55674537
  87      1.280 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.gui.dialogs.flightconfiguration.MotorMountTableModel@4ab8dabd, current number of listeners is 7
  88      1.287 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.FlightConfigurableTableModel@40a6a86e, current number of listeners is 8
  89      1.292 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.gui.main.flightconfigpanel.SeparationConfigurationPanel$3@322ca1f6, current number of listeners is 9
  90      1.322 DEBUG  (RocketFigure3d.java:138) Initializing RocketFigure3D OpenGL Canvas
  91      1.322 DEBUG  (RocketFigure3d.java:140) Setting up GL capabilities...
  92      1.322 VBOSE  (RocketFigure3d.java:142) GL - Getting Default Profile
  93      1.548 STDERR (TraceException.java:26) javax.media.opengl.GLException: X11GLXDrawableFactory - Could not initialize shared resources for :0
  94      1.548 STDERR (TraceException.java:26) 	at jogamp.opengl.x11.glx.X11GLXDrawableFactory$SharedResourceImplementation.createSharedResource(X11GLXDrawableFactory.java:316)
  95      1.548 STDERR (TraceException.java:26) 	at jogamp.opengl.SharedResourceRunner.run(SharedResourceRunner.java:295)
  96      1.548 STDERR (TraceException.java:26) 	at java.lang.Thread.run(Thread.java:748)
  97      1.548 STDERR (TraceException.java:26) Caused by: java.lang.NullPointerException
  98      1.548 STDERR (TraceException.java:26) 	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:597)
  99      1.548 STDERR (TraceException.java:26) 	at jogamp.opengl.GLContextImpl.makeCurrent(GLContextImpl.java:518)
 100      1.548 STDERR (TraceException.java:26) 	at jogamp.opengl.x11.glx.X11GLXDrawableFactory$SharedResourceImplementation.createSharedResource(X11GLXDrawableFactory.java:292)
 101      1.548 STDERR (TraceException.java:26) 	... 2 more
 102      1.550 VBOSE  (RocketFigure3d.java:145) GL - creating GLCapabilities
 103      1.550 VBOSE  (RocketFigure3d.java:149) GL - setSampleBuffers
 104      1.550 VBOSE  (RocketFigure3d.java:152) GL - setNumSamples
 105      1.550 VBOSE  (RocketFigure3d.java:162) GL - Creating GLCanvas
 106      1.556 VBOSE  (RocketFigure3d.java:166) GL - Registering as GLEventListener on canvas
 107      1.556 VBOSE  (RocketFigure3d.java:169) GL - Adding canvas to this JPanel
 108      1.556 VBOSE  (RocketFigure3d.java:172) GL - Setting up mouse listeners
 109      1.556 VBOSE  (RocketFigure3d.java:175) GL - Rasterizing Carets
 110      1.569 VBOSE  (DoubleModel.java:890) DoubleModel[constant=0.0] adding listener (total 1): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$1@58dd6817
 111      1.570 VBOSE  (DoubleModel.java:890) DoubleModel[constant=0.0] adding listener (total 2): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler$1@70ee31b4
 112      1.570 VBOSE  (DoubleModel.java:890) DoubleModel[constant=0.0] adding listener (total 3): net.sf.openrocket.gui.scalefigure.ScaleScrollPane$Ruler$1@3bb0f821
 113      1.584 VBOSE  (DoubleModel.java:890) DoubleModel[RocketFigure:Rotation] adding listener (total 1): net.sf.openrocket.gui.components.UnitSelector[,0,0,0x0,invalid,alignmentX=0.0,alignmentY=0.0,border=javax.swing.plaf.synth.SynthBorder@73a7ebe3,flags=8388608,maximumSize=,minimumSize=,preferredSize=,defaultIcon=,disabledIcon=,horizontalAlignment=LEADING,horizontalTextPosition=TRAILING,iconTextGap=4,labelFor=,text=,verticalAlignment=CENTER,verticalTextPosition=CENTER]
 114      1.585 VBOSE  (DoubleModel.java:890) DoubleModel[RocketFigure:Rotation] adding listener (total 2): javax.swing.JSlider$ModelListener@7383c382
 115      1.586 VBOSE  (DoubleModel.java:890) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@67ecadc2
 116      1.588 VBOSE  (DoubleModel.java:915) DoubleModel[RocketFigure:Rotation] removing listener (total 2): javax.swing.plaf.basic.BasicSliderUI$Handler@67ecadc2
 117      1.588 VBOSE  (DoubleModel.java:890) DoubleModel[RocketFigure:Rotation] adding listener (total 3): javax.swing.plaf.basic.BasicSliderUI$Handler@3f824c13
 118      1.677 DEBUG  (AbstractAerodynamicCalculator.java:98) Voiding the aerodynamic cache
 119      1.681 DEBUG  (AbstractMassCalculator.java:36) Voiding the mass cache
 120      1.683 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.gui.scalefigure.RocketPanel$4@1eb6f0e0, current number of listeners is 10
 121      1.691 DEBUG  (JarUtil.java:40) Found jar file using codeSource
 122      1.691 DEBUG  (ExampleDesignFile.java:115) Current jar file is: /home/mrnic3/OpenRocket-15.03-nopresets.jar
 123      1.698 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.util.ComponentChangeAdapter@378ddc16, current number of listeners is 11
 124      1.704 VBOSE  (Rocket.java:357) Added ComponentChangeListener net.sf.openrocket.gui.main.BasicFrame$1@440d4f71, current number of listeners is 12
 125      1.772 DEBUG  (BasicFrame.java:265) BasicFrame instantiation complete
 126      1.779 INFO   (SwingStartup.java:194) Checking update status
 127      1.779 INFO   (SwingStartup.java:83) Startup complete
 128      1.779 INFO   (SwingExceptionHandler.java:201) Showing Exception dialog
 129      1.857 DEBUG  (GUIUtil.java:310) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=3373,height=1264]
 130      1.857 DEBUG  (GUIUtil.java:314) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
 131      1.863 DEBUG  (GUIUtil.java:310) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=3373,height=1264]
 132      1.863 DEBUG  (GUIUtil.java:314) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
 133      1.869 DEBUG  (GUIUtil.java:310) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=3373,height=1264]
 134      1.869 DEBUG  (GUIUtil.java:314) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
 135      1.869 DEBUG  (GUIUtil.java:310) Storing size of net.sf.openrocket.gui.main.BasicFrame: java.awt.Dimension[width=3373,height=1264]
 136      1.869 DEBUG  (GUIUtil.java:314) Storing maximized state of net.sf.openrocket.gui.main.BasicFrame
 137      4.966 USER   (SwingExceptionHandler.java:220) User requested sending bug report
 138      4.968 DEBUG  (JarUtil.java:40) Found jar file using codeSource
---------- End of bug report ----------

**Comment by mrnic3** [comment]
It happens as the last component is missing an centeringring opening tag on the github repository

**Comment by dbcook** [comment]
Confirmed, thank you!  I switched to vscode a while back and silently lost my in-editor XML validation. oops.  Fix coming shortly.

**Comment by dbcook** [comment]
Fix pushed in bluetube.orc.  Thanks for letting me know.
