### ISSUE TITLE
Estes Body tubes missing

### ISSUE THREAD

**Issue by ghost** [dbcook/openrocket-database#4]
While trying to model the Black Star Voyager model, I found 3 body tubes missing. They are documented in the Black Star Voyager Instructions. All are Estes body tubes, and all are paper. Validated from the model I own

Part No.              OD:       ID:        Length
030374 (BT-55)   1.325    1.283   10.75
030365 (BT-50)   0.976    0.950   17.75
031776               1.44      1.39      5.7
[007222_BLACK_STAR_VOYAGER.pdf](https://github.com/dbcook/openrocket-database/files/8235891/007222_BLACK_STAR_VOYAGER.pdf)
5

**Comment by dbcook** [comment]
Fixed, thanks!  PN 30374 was already in the database. Note that Estes erroneously used it twice for two different tubes.  Added PN 30365 with the 17.75" length and 31776.  PN 30365 has also been used before for BT-50P which is 11.0" long, so it's another collision.  The size with OD 1.44 has never been recorded before.
