### ISSUE TITLE
Nose Cone Missing

### ISSUE THREAD

**Issue by ghost** [dbcook/openrocket-database#5]
The nose cone for the Black Star Voyager is missing. This is a strange, ribbed nose cone so it would be difficult to model, but you could create a base code without the ribs.
072773 (fits BT-55)  Base 1.325  Length 5.25" shoulder:1.283 base, length 0.75  shapr:OGIVE

**Comment by dbcook** [comment]
Can you weigh it to 1 gram or so and post the mass (including the cap)?  I can't list it without some decent idea of the mass, though by comparison with the similar old PNC-55AC/71070 (5.375" long) it ought to be in the 9-12gm range.

**Comment by dbcook** [comment]
Another question - is it blow molded or injection molded?  Injection molded ones will have a more noticeable and sharper seam down the side.

**Comment by ghost** [comment]
I am sorry I meant to write PNC-55AC. It appears to be blow molded, 12 grams

**Comment by dbcook** [comment]
NC added to estes_classic.orc.  It won't display with the ribs, but the drag will be fairly close and the mass is correct.

**Comment by ghost** [comment]
Thanks
