### ISSUE TITLE
Estes Body

### ISSUE THREAD

**Issue by ghost** [dbcook/openrocket-database#6]
Estes Body Tube part number 072773 is missing. It appear to be identical to BT-50S

**Comment by dbcook** [comment]
I'm confused - 72773 is the BSV nose cone.  I don't see anything in the parts list that looks like the 4.0" long BT-50S.

**Comment by dbcook** [comment]
I'm going to close this issue because I think has been taken care of by the other two from today.

But there is one more item - if you could provide dimensions and weight for the 66633 tube adapter, we'll have a complete set from the BSV!

**Comment by ghost** [comment]
Well, its an assembled kit so it going to be difficult Transition goes from 1.44" to BT-55 1.35" length is 1.25" can't tell you the shoulder length. the large end shoulder shoulder should be 1.39" Can't tell you the weight.

**Comment by dbcook** [comment]
Wow that's for the novel 1.44" tube!  Too bad it's glued in now.  I can probably estimate the shoulder length and likely weight by assuming about a .050 wall with density of styrene.  The length is most critical for the shape and you've got that. Stay tuned for update.

**Comment by dbcook** [comment]
Added transition PN 66633 as described in previous comments here.  I took the shoulder lengths as 0.75" which seems to match the drawing in the instructions.

**Comment by ghost** [comment]
Thank you very much for such a quick turn around. I created my own orc to contain these until the next version shows up.
