### ISSUE TITLE
"m" showing as unit in place of "mm" and "in" in several orcs

### ISSUE THREAD

**Issue by questionablerocket** [dbcook/openrocket-database#8]
Thank you for the hard work compiling and maintaining this database.  In working with your database, I found a few cases where meters are used as the unit of measure in place of inches or millimeters.

In https://github.com/dbcook/openrocket-database/blob/master/orc/estes_classic.orc :

PNC-20, 072606 shows:

            <OutsideDiameter Unit="m">0.736</OutsideDiameter>
            <ShoulderDiameter Unit="m">0.710</ShoulderDiameter>

I believe these should be:

            <OutsideDiameter Unit="in">0.736</OutsideDiameter>
            <ShoulderDiameter Unit="in">0.710</ShoulderDiameter>

In https://github.com/dbcook/openrocket-database/blob/master/orc/loc_precision.orc :

Both BT-5.38 and FT-5.38 show: 

            <OutsideDiameter Unit="m">5.54</OutsideDiameter>

I believe they should be:

            <OutsideDiameter Unit="in">5.54</OutsideDiameter>

TC-7.51-15 shows:

            <Length Unit="m">15.0</Length>

I believe this should be:

            <Length Unit="in">15.0</Length>

In https://github.com/dbcook/openrocket-database/blob/master/orc/publicmissiles.orc :

CT-1.5 shows:

            <OutsideDiameter Unit="m">1.525</OutsideDiameter>

I believe this should be:

            <OutsideDiameter Unit="in">1.525</OutsideDiameter>

In https://github.com/dbcook/openrocket-database/blob/master/orc/quest.orc :

Both Q28700 and 25mm_red_tint_payload_tube show: 

            <OutsideDiameter Unit="m">25.0</OutsideDiameter>

I believe these should be:

            <OutsideDiameter Unit="mm">25.0</OutsideDiameter>

Q14103 shows:

            <OutsideDiameter Unit="m">28.9</OutsideDiameter>

I believe this should be:

            <OutsideDiameter Unit="mm">28.9</OutsideDiameter>

PNC30, Q20304 shows:

            <ShoulderDiameter Unit="m">28.9</ShoulderDiameter>

I believe this should be:

            <ShoulderDiameter Unit="mm">28.9</ShoulderDiameter>

**Comment by questionablerocket** [comment]
Pull request opened for this:

https://github.com/dbcook/openrocket-database/pull/9

**Comment by dbcook** [comment]
Good finds!  A massive number of the parts had to have their units converted from m (the original OR file had everything in meters no matter how the manufacturer specified things) and it looks like a few slipped through.  I'll check out the PR and merge it if all looks well.

**Comment by dbcook** [comment]
Merged PR8

**Comment by questionablerocket** [comment]
Thanks!  Glad to have helped.

I checked every orc except for Giant Leap, where all the units were meters, and I didn't have the eye-ball strength to look through them all.  Now I understand why that file is like that.  :-)
